// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncwffeqtbmjfxgwmaqin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jd2ZmZXF0Ym1qZnhnd21hcWluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMDY4OTUsImV4cCI6MjA2MTU4Mjg5NX0.OhrHkqtYuKBKMSJNjBZwXSeTXL-tbXSJ3AwFgSrtrys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);